# Generated by Django 4.0.3 on 2022-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_petstagramuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
