# Generated by Django 3.2.3 on 2021-06-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_like'),
        ('common', '0003_auto_20210622_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentNew',
            new_name='Comment',
        ),
    ]
